<a href="https://colab.research.google.com/github/IndraP24/Course-LabWorks/blob/main/ANN/Lab%20Activity%20-%207%20-%20ANN_Class_Activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import libraries

In [ ]:
import pandas as pd
import numpy as np

# Read data

In [ ]:
df1 = pd.read_csv('myFile0.csv')
df2 = pd.read_csv('myFile1.csv')
print(df1.shape, df2.shape)

(1000, 4) (1000, 4)


In [ ]:
df1.head()

id    1    2    3
0  100  876  372   47
1  101  500  230  841
2  102  526  563  797
3  103  489  378   75
4  104  488  669  933

In [ ]:
df2.head()

id    1    2    3
0  100  318  240  732
1  101  314  288   75
2  102  778  981  215
3  103  353  231  177
4  104  712  472  636

# Convert `DataFrame` to numpy `array`

In [ ]:
m1 = df1.values
m2 = df2.values
print(m1.shape, m2.shape)

(1000, 4) (1000, 4)


In [ ]:
m1

array([[ 100,  876,  372,   47],
       [ 101,  500,  230,  841],
       [ 102,  526,  563,  797],
       ...,
       [1097,  667,  506,  577],
       [1098,  156,  917,  108],
       [1099,  704,  577,  132]])

In [ ]:
m2

array([[ 100,  318,  240,  732],
       [ 101,  314,  288,   75],
       [ 102,  778,  981,  215],
       ...,
       [1097,  874,  807,  526],
       [1098,  845,  491,  286],
       [1099,  971,  822,  562]])

In [ ]:
m3 = m2.T
print(m3.shape)
m3

(4, 1000)


array([[ 100,  101,  102, ..., 1097, 1098, 1099],
       [ 318,  314,  778, ...,  874,  845,  971],
       [ 240,  288,  981, ...,  807,  491,  822],
       [ 732,   75,  215, ...,  526,  286,  562]])

# Matrix Operations

### Matrix Addition

In [ ]:
def matadd(m1: np.ndarray, m2: np.ndarray):
    """Adds two matrix after checking possibility."""
    if m1.shape == m2.shape:
        return m1+m2
    else:
        return "Addition not possible because of inconsistent shape"

In [ ]:
matadd(m1, m2)

array([[ 200, 1194,  612,  779],
       [ 202,  814,  518,  916],
       [ 204, 1304, 1544, 1012],
       ...,
       [2194, 1541, 1313, 1103],
       [2196, 1001, 1408,  394],
       [2198, 1675, 1399,  694]])

In [ ]:
matadd(m1, m3)

'Addition not possible because of inconsistent shape'

### Matrix Multiplication

In [ ]:
def matmul(m1: np.ndarray, m2: np.ndarray):
    """Multiplies two matrix after checking possibility."""
    if m1.shape[0] == m2.shape[1]:
        return m1 @ m2
    else:
        return "Multiplication not possible because of inconsistent shape"

In [ ]:
matmul(m1, m3)

array([[ 412252,  395825, 1066765, ..., 1200250, 1046114, 1292694],
       [ 839912,  296516,  805747, ..., 1175773,  886854, 1258201],
       [ 895992,  397385, 1143290, ..., 1445181, 1060841, 1533544],
       ...,
       [ 865610,  509238, 1251261, ..., 2498211, 2181589, 2593466],
       [ 458544,  432078, 1156161, ..., 2137677, 1818559, 2172648],
       [ 568876,  508131, 1254227, ..., 2355970, 2122641, 2439863]])

In [ ]:
matmul(m1, m2)

'Multiplication not possible because of inconsistent shape'